{{-- ==========================================================
PAGE NO : 7

FILE:
resources/views/reports/print.blade.php

PURPOSE:
Printable Test Report

========================================================== --}}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>Lab Automation System - Test Report</title>

    <style>

        /* ==========================================
           GLOBAL STYLE
        ========================================== */

        *{
            margin:0;
            padding:0;
            box-sizing:border-box;
        }

        body{

            font-family:Arial, Helvetica, sans-serif;
            background:#ffffff;
            color:#222;
            padding:30px;

        }

        .container{

            width:100%;
            margin:auto;

        }

        /* ==========================================
           HEADER
        ========================================== */

        .header{

            display:flex;
            justify-content:space-between;
            align-items:center;

            border-bottom:3px solid #0d6efd;

            padding-bottom:20px;

            margin-bottom:30px;

        }

        .logo{

            width:100px;

        }

        .logo img{

            width:100%;

        }

        .title{

            flex:1;

            text-align:center;

        }

        .title h1{

            font-size:30px;

            color:#0d6efd;

            margin-bottom:8px;

        }

        .title h3{

            font-size:18px;

            color:#555;

        }

        .print-date{

            text-align:right;

            font-size:14px;

        }

        hr{

            margin-top:15px;
            margin-bottom:20px;

        }

    </style>

</head>

<body>

<div class="container">

    {{-- ==========================================
         HEADER
    ========================================== --}}

    <div class="header">

        <div class="logo">

            {{-- Logo from public/images/logo.jpeg --}}
            <img src="{{ asset('images/logo.jpeg') }}"
                 alt="Company Logo">

        </div>

        <div class="title">

            <h1>LAB AUTOMATION SYSTEM</h1>

            <h3>Electrical Testing Report</h3>

        </div>

        <div class="print-date">

            <strong>Date</strong><br>

            {{ date('d-M-Y') }}

            <br><br>

            <strong>Time</strong><br>

            {{ date('h:i A') }}

        </div>

    </div>

    <hr>

    {{-- ==========================================
         REPORT INFORMATION
    ========================================== --}}

    <table style="width:100%;border-collapse:collapse;margin-bottom:25px;">

        <tr>

            <td style="padding:10px;border:1px solid #ccc;">
                <strong>Report Year</strong>
            </td>

            <td style="padding:10px;border:1px solid #ccc;">
                {{ $year }}
            </td>

            <td style="padding:10px;border:1px solid #ccc;">
                <strong>Generated By</strong>
            </td>

            <td style="padding:10px;border:1px solid #ccc;">
                Administrator
            </td>

        </tr>

        <tr>

            <td style="padding:10px;border:1px solid #ccc;">
                <strong>Generated On</strong>
            </td>

            <td style="padding:10px;border:1px solid #ccc;">
                {{ date('d-M-Y h:i A') }}
            </td>

            <td style="padding:10px;border:1px solid #ccc;">
                <strong>Status</strong>
            </td>

            <td style="padding:10px;border:1px solid #ccc;">
                Final Report
            </td>

        </tr>

    </table>


    {{-- ==========================================
         SUMMARY CARDS
    ========================================== --}}

    <table style="width:100%;border-collapse:collapse;margin-bottom:30px;">

        <tr>

            <td style="width:20%;padding:15px;border:1px solid #333;text-align:center;">

                <h3>Total Tests</h3>

                <h1>{{ $totalTests }}</h1>

            </td>

            <td style="width:20%;padding:15px;border:1px solid #333;text-align:center;">

                <h3>Passed</h3>

                <h1>{{ $passedTests }}</h1>

            </td>

            <td style="width:20%;padding:15px;border:1px solid #333;text-align:center;">

                <h3>Failed</h3>

                <h1>{{ $failedTests }}</h1>

            </td>

            <td style="width:20%;padding:15px;border:1px solid #333;text-align:center;">

                <h3>Pending</h3>

                <h1>{{ $pendingTests }}</h1>

            </td>

            <td style="width:20%;padding:15px;border:1px solid #333;text-align:center;">

                <h3>Pass Rate</h3>

                <h1>{{ $passRate }}%</h1>

            </td>

        </tr>

    </table>


    {{-- ==========================================
         REPORT TITLE
    ========================================== --}}

    <h2 style="text-align:center;margin-bottom:20px;">

        COMPLETE TEST REPORT

    </h2>

    <p style="text-align:center;margin-bottom:35px;">

        This report contains all laboratory testing records for the selected
        year including pass, fail and pending results.

    </p>
        {{-- ==========================================
         TEST REPORT TABLE
    ========================================== --}}

    <table style="
        width:100%;
        border-collapse:collapse;
        margin-top:20px;
        margin-bottom:30px;
    ">

        <thead>

            <tr style="background:#0d6efd;color:#ffffff;">

                <th style="border:1px solid #000;padding:10px;">#</th>

                <th style="border:1px solid #000;padding:10px;">
                    Product Name
                </th>

                <th style="border:1px solid #000;padding:10px;">
                    Test Type
                </th>

                <th style="border:1px solid #000;padding:10px;">
                    Engineer
                </th>

                <th style="border:1px solid #000;padding:10px;">
                    Result
                </th>

                <th style="border:1px solid #000;padding:10px;">
                    Test Date
                </th>

            </tr>

        </thead>

        <tbody>

        @forelse($tests as $index => $test)

            <tr>

                <td style="border:1px solid #000;padding:8px;text-align:center;">

                    {{ $index + 1 }}

                </td>

                <td style="border:1px solid #000;padding:8px;">

                    {{ $test->product_name }}

                </td>

                <td style="border:1px solid #000;padding:8px;">

                    {{ $test->test_type }}

                </td>

                <td style="border:1px solid #000;padding:8px;">

                    {{ $test->engineer_name }}

                </td>

                <td style="
                    border:1px solid #000;
                    padding:8px;
                    text-align:center;
                    font-weight:bold;
                ">

                    @if($test->result == 'pass')

                        PASS

                    @elseif($test->result == 'fail')

                        FAIL

                    @else

                        PENDING

                    @endif

                </td>

                <td style="border:1px solid #000;padding:8px;">

                    {{ date('d-M-Y', strtotime($test->created_at)) }}

                </td>

            </tr>

        @empty

            <tr>

                <td colspan="6"
                    style="
                        border:1px solid #000;
                        padding:20px;
                        text-align:center;
                    ">

                    No Test Records Found

                </td>

            </tr>

        @endforelse

        </tbody>

    </table>
        {{-- ==========================================
         REPORT FOOTER
    ========================================== --}}

    <br><br>

    <table style="width:100%;margin-top:40px;">

        <tr>

            <td style="width:45%;text-align:center;">

                <br><br><br>

                <hr>

                <strong>Prepared By</strong>

            </td>

            <td style="width:10%;"></td>

            <td style="width:45%;text-align:center;">

                <br><br><br>

                <hr>

                <strong>Approved By</strong>

            </td>

        </tr>

    </table>


    {{-- ==========================================
         FOOTER
    ========================================== --}}

    <div style="
        margin-top:40px;
        text-align:center;
        font-size:13px;
        color:#666;
    ">

        <p>

            <strong>Lab Automation System</strong>

        </p>

        <p>

            Electrical Testing Management System

        </p>

        <p>

            This is a computer generated report and does not require a manual signature.

        </p>

        <p>

            Generated on {{ date('d M Y') }} at {{ date('h:i A') }}

        </p>

    </div>

</div>

{{-- ==========================================
     PRINT STYLE
========================================== --}}

<style>

@media print{

    @page{

        size:A4;
        margin:15mm;

    }

    body{

        background:#fff;

        -webkit-print-color-adjust:exact;
        print-color-adjust:exact;

    }

}

</style>

{{-- ==========================================
     AUTO PRINT
========================================== --}}

<script>

window.onload=function(){

    window.print();

};

</script>

</body>

</html>

<script>
window.print();
</script>